-- MySQL Script generated by MySQL Workbench
-- 04/19/16 17:43:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `idarea` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(60) NULL COMMENT '',
  `iddepto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idarea`, `iddepto`)  COMMENT '',
  INDEX `fk_area_depto_idx` (`iddepto` ASC)  COMMENT '',
  CONSTRAINT `fk_area_depto`
    FOREIGN KEY (`iddepto`)
    REFERENCES `mydb`.`depto` (`iddepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`depto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`depto` (
  `iddepto` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(60) NULL COMMENT '',
  PRIMARY KEY (`iddepto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `idarea` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(60) NULL COMMENT '',
  `iddepto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idarea`, `iddepto`)  COMMENT '',
  INDEX `fk_area_depto_idx` (`iddepto` ASC)  COMMENT '',
  CONSTRAINT `fk_area_depto`
    FOREIGN KEY (`iddepto`)
    REFERENCES `mydb`.`depto` (`iddepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personal` (
  `idpersonal` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(60) NULL COMMENT '',
  `appaterno` VARCHAR(60) NULL COMMENT '',
  `apmaterno` VARCHAR(60) NULL COMMENT '',
  `correo` VARCHAR(60) NULL COMMENT '',
  `contrasena` VARCHAR(20) NULL COMMENT '',
  `iddepto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idpersonal`, `iddepto`)  COMMENT '',
  INDEX `fk_personal_depto1_idx` (`iddepto` ASC)  COMMENT '',
  CONSTRAINT `fk_personal_depto1`
    FOREIGN KEY (`iddepto`)
    REFERENCES `mydb`.`depto` (`iddepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interesado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interesado` (
  `idinteresado` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(60) NULL COMMENT '',
  `appaterno` VARCHAR(60) NULL COMMENT '',
  `apmaterno` VARCHAR(60) NULL COMMENT '',
  `correo` VARCHAR(60) NULL COMMENT '',
  `telefono` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`idinteresado`)  COMMENT '')
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Solicitud Token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SolicitudToken` (
  `token` varchar(64) NOT NULL,
   `idSolicitud` INT NOT NULL COMMENT '',
  -- PRIMARY KEY (`idpersonal`, `iddepto`)  COMMENT '',
  INDEX `fk_solicitudtoken1_idx` (`idSolicitud` ASC)  COMMENT '',
  CONSTRAINT `fk_solicitudtoken1`
    FOREIGN KEY (`idSolicitud`)
    REFERENCES `mydb`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitud` (
  `idSolicitud` INT NOT NULL AUTO_INCREMENT,
  `asunto` VARCHAR(60) NULL COMMENT '',
  `estado` VARCHAR(20) NULL COMMENT '',
  `idinteresado` INT NOT NULL COMMENT '',
  `idarea` INT NOT NULL COMMENT '',
  `iddepto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idSolicitud`, `idinteresado`, `idarea`, `iddepto`)  COMMENT '',
  INDEX `fk_Solicitud_interesado1_idx` (`idinteresado` ASC)  COMMENT '',
  INDEX `fk_Solicitud_area1_idx` (`idarea` ASC, `iddepto` ASC)  COMMENT '',
  CONSTRAINT `fk_Solicitud_interesado1`
    FOREIGN KEY (`idinteresado`)
    REFERENCES `mydb`.`interesado` (`idinteresado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_area1`
    FOREIGN KEY (`idarea` , `iddepto`)
    REFERENCES `mydb`.`area` (`idarea` , `iddepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HoraPref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HoraPref` (
  `idHorario` INT NOT NULL COMMENT '',
  `hinicio` TIME NULL COMMENT '',
  `hfin` TIME NULL COMMENT '',
  PRIMARY KEY (`idHorario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HoraSol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HoraSol` (
  `idHorario` INT NOT NULL COMMENT '',
  `idSolicitud` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idHorario`, `idSolicitud`)  COMMENT '',
  INDEX `fk_Horario_has_Solicitud_Solicitud1_idx` (`idSolicitud` ASC)  COMMENT '',
  INDEX `fk_Horario_has_Solicitud_Horario1_idx` (`idHorario` ASC)  COMMENT '',
  CONSTRAINT `fk_Horario_has_Solicitud_Horario1`
    FOREIGN KEY (`idHorario`)
    REFERENCES `mydb`.`HoraPref` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_has_Solicitud_Solicitud1`
    FOREIGN KEY (`idSolicitud`)
    REFERENCES `mydb`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DiaPref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DiaPref` (
  `idDia` INT NOT NULL COMMENT '',
  `dia` DATE NULL COMMENT '',
  PRIMARY KEY (`idDia`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DiaSol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DiaSol` (
  `idDia` INT NOT NULL COMMENT '',
  `idSolicitud` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idDia`, `idSolicitud`)  COMMENT '',
  INDEX `fk_Dia_has_Solicitud_Solicitud1_idx` (`idSolicitud` ASC)  COMMENT '',
  INDEX `fk_Dia_has_Solicitud_Dia1_idx` (`idDia` ASC)  COMMENT '',
  CONSTRAINT `fk_Dia_has_Solicitud_Dia1`
    FOREIGN KEY (`idDia`)
    REFERENCES `mydb`.`DiaPref` (`idDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dia_has_Solicitud_Solicitud1`
    FOREIGN KEY (`idSolicitud`)
    REFERENCES `mydb`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(60) NULL COMMENT '',
  `asunto` VARCHAR(30) NULL COMMENT '',
  `contenido` VARCHAR(200) NULL COMMENT '',
  `estado` VARCHAR(20) NULL COMMENT '',
  `depto_iddepto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idMensaje`, `depto_iddepto`)  COMMENT '',
  INDEX `fk_Mensaje_depto1_idx` (`depto_iddepto` ASC)  COMMENT '',
  CONSTRAINT `fk_Mensaje_depto1`
    FOREIGN KEY (`depto_iddepto`)
    REFERENCES `mydb`.`depto` (`iddepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT,
  `hinicio` TIME NULL COMMENT '',
  `hfin` TIME NULL COMMENT '',
  `dia` DATE NULL COMMENT '',
  `idarea` INT NOT NULL COMMENT '',
  `iddepto` INT NOT NULL COMMENT '',
  `idinteresado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCita`, `idarea`, `iddepto`, `idinteresado`)  COMMENT '',
  INDEX `fk_Cita_area1_idx` (`idarea` ASC, `iddepto` ASC)  COMMENT '',
  INDEX `fk_Cita_interesado1_idx` (`idinteresado` ASC)  COMMENT '',
  CONSTRAINT `fk_Cita_area1`
    FOREIGN KEY (`idarea` , `iddepto`)
    REFERENCES `mydb`.`area` (`idarea` , `iddepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_interesado1`
    FOREIGN KEY (`idinteresado`)
    REFERENCES `mydb`.`interesado` (`idinteresado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
