-- MySQL Script generated by MySQL Workbench
-- 05/11/16 00:25:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `idarea` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(60) NULL COMMENT '',
  `iddepto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idarea`, `iddepto`)  COMMENT '',
  INDEX `fk_area_depto_idx` (`iddepto` ASC)  COMMENT '',
  CONSTRAINT `fk_area_depto`
    FOREIGN KEY (`iddepto`)
    REFERENCES `mydb`.`depto` (`iddepto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personal` (
  `idpersonal` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(60) NULL COMMENT '',
  `appaterno` VARCHAR(60) NULL COMMENT '',
  `apmaterno` VARCHAR(60) NULL COMMENT '',
  `correo` VARCHAR(60) NULL COMMENT '',
  `contrasena` BLOB NULL COMMENT '',
  `cargo` INT(5) NULL COMMENT '',
  PRIMARY KEY (`idpersonal`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`depto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`depto` (
  `iddepto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(60) NULL COMMENT '',
  `idpersonal` INT NOT NULL COMMENT '',
  PRIMARY KEY (`iddepto`, `idpersonal`)  COMMENT '',
  INDEX `fk_depto_personal1_idx` (`idpersonal` ASC)  COMMENT '',
  CONSTRAINT `fk_depto_personal1`
    FOREIGN KEY (`idpersonal`)
    REFERENCES `mydb`.`personal` (`idpersonal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `idarea` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(60) NULL COMMENT '',
  `iddepto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idarea`, `iddepto`)  COMMENT '',
  INDEX `fk_area_depto_idx` (`iddepto` ASC)  COMMENT '',
  CONSTRAINT `fk_area_depto`
    FOREIGN KEY (`iddepto`)
    REFERENCES `mydb`.`depto` (`iddepto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interesado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interesado` (
  `idinteresado` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(60) NULL COMMENT '',
  `appaterno` VARCHAR(60) NULL COMMENT '',
  `apmaterno` VARCHAR(60) NULL COMMENT '',
  `correo` VARCHAR(60) NULL COMMENT '',
  `telefono` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`idinteresado`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitud` (
  `idSolicitud` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `asunto` VARCHAR(60) NULL COMMENT '',
  `estado` VARCHAR(20) NULL COMMENT '',
  `dia` VARCHAR(20) NULL COMMENT '',
  `idinteresado` INT NOT NULL COMMENT '',
  `idarea` INT NOT NULL COMMENT '',
  `iddepto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idSolicitud`, `idinteresado`, `idarea`, `iddepto`)  COMMENT '',
  INDEX `fk_Solicitud_interesado1_idx` (`idinteresado` ASC)  COMMENT '',
  INDEX `fk_Solicitud_area1_idx` (`idarea` ASC, `iddepto` ASC)  COMMENT '',
  CONSTRAINT `fk_Solicitud_interesado1`
    FOREIGN KEY (`idinteresado`)
    REFERENCES `mydb`.`interesado` (`idinteresado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Solicitud_area1`
    FOREIGN KEY (`idarea` , `iddepto`)
    REFERENCES `mydb`.`area` (`idarea` , `iddepto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horapref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horapref` (
  `idHorario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `hinicio` VARCHAR(20) NULL COMMENT '',
  `hfin` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`idHorario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horasol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horasol` (
  `idHorario` INT NOT NULL COMMENT '',
  `idSolicitud` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idHorario`, `idSolicitud`)  COMMENT '',
  INDEX `fk_Horario_has_Solicitud_Solicitud1_idx` (`idSolicitud` ASC)  COMMENT '',
  INDEX `fk_Horario_has_Solicitud_Horario1_idx` (`idHorario` ASC)  COMMENT '',
  CONSTRAINT `fk_Horario_has_Solicitud_Horario1`
    FOREIGN KEY (`idHorario`)
    REFERENCES `mydb`.`horapref` (`idHorario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Horario_has_Solicitud_Solicitud1`
    FOREIGN KEY (`idSolicitud`)
    REFERENCES `mydb`.`solicitud` (`idSolicitud`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `correo` VARCHAR(60) NULL COMMENT '',
  `asunto` VARCHAR(30) NULL COMMENT '',
  `contenido` VARCHAR(200) NULL COMMENT '',
  `estado` VARCHAR(20) NULL COMMENT '',
  `fecha` VARCHAR(20) NULL COMMENT '',
  `iddepto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idMensaje`, `iddepto`)  COMMENT '',
  INDEX `fk_Mensaje_depto1_idx` (`iddepto` ASC)  COMMENT '',
  CONSTRAINT `fk_Mensaje_depto1`
    FOREIGN KEY (`iddepto`)
    REFERENCES `mydb`.`depto` (`iddepto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `turno` VARCHAR(1) NULL COMMENT '',
  `hinicio` VARCHAR(20) NULL COMMENT '',
  `hfin` VARCHAR(20) NULL COMMENT '',
  `dia` VARCHAR(20) NULL COMMENT '',
  `idarea` INT NOT NULL COMMENT '',
  `iddepto` INT NOT NULL COMMENT '',
  `idinteresado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCita`, `idarea`, `iddepto`, `idinteresado`)  COMMENT '',
  INDEX `fk_Cita_area1_idx` (`idarea` ASC, `iddepto` ASC)  COMMENT '',
  INDEX `fk_Cita_interesado1_idx` (`idinteresado` ASC)  COMMENT '',
  CONSTRAINT `fk_Cita_area1`
    FOREIGN KEY (`idarea` , `iddepto`)
    REFERENCES `mydb`.`area` (`idarea` , `iddepto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cita_interesado1`
    FOREIGN KEY (`idinteresado`)
    REFERENCES `mydb`.`interesado` (`idinteresado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitudtoken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitudtoken` (
  `idtoken` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `token` VARCHAR(20) NULL COMMENT '',
  `idSolicitud` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtoken`, `idSolicitud`)  COMMENT '',
  INDEX `fk_solicitudtoken_Solicitud1_idx` (`idSolicitud` ASC)  COMMENT '',
  CONSTRAINT `fk_solicitudtoken_Solicitud1`
    FOREIGN KEY (`idSolicitud`)
    REFERENCES `mydb`.`solicitud` (`idSolicitud`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
